spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据驱动
    password: shen0720
    url: jdbc:mysql://localhost:3306/sjz?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    database: mysql # 数据库类型
    hibernate:
      ddl-auto: update # 如果数据库中存在表就不创建
    properties:
      hibernate:
        format_sql: true
    show-sql: true # 是否显示SQL语句
  mail:
    host: smtp.163.com
    username: shenbw1996@163.com
    password: ULJHPDSKKKFKSLSD
    default-encoding: utf-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false


server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
